//
// Autogenerated by Thrift Compiler (0.19.0)
//
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
//
import thrift = require('thrift');
import Thrift = thrift.Thrift;
import Q = thrift.Q;
import Int64 = require('node-int64');
import common_ttypes = require('./common_types');



declare class ProfilingStats {
    public rows: Int64;
    public exec_duration_in_us: Int64;
    public total_duration_in_us: Int64;
    public other_stats?: any;

      constructor(args?: { rows: Int64; exec_duration_in_us: Int64; total_duration_in_us: Int64; other_stats?: any; });
  }

declare class PlanNodeBranchInfo {
    public is_do_branch: boolean;
    public condition_node_id: Int64;

      constructor(args?: { is_do_branch: boolean; condition_node_id: Int64; });
  }

declare class Pair {
    public key: Buffer;
    public value: Buffer;

      constructor(args?: { key: Buffer; value: Buffer; });
  }

declare class PlanNodeDescription {
    public name: Buffer;
    public id: Int64;
    public output_var: Buffer;
    public description?: Pair[];
    public profiles?: ProfilingStats[];
    public branch_info?: PlanNodeBranchInfo;
    public dependencies?: Int64[];

      constructor(args?: { name: Buffer; id: Int64; output_var: Buffer; description?: Pair[]; profiles?: ProfilingStats[]; branch_info?: PlanNodeBranchInfo; dependencies?: Int64[]; });
  }

declare class PlanDescription {
    public plan_node_descs: PlanNodeDescription[];
    public node_index_map: any;
    public format: Buffer;
    public optimize_time_in_us: number;

      constructor(args?: { plan_node_descs: PlanNodeDescription[]; node_index_map: any; format: Buffer; optimize_time_in_us: number; });
  }

declare class ExecutionResponse {
    public error_code: common_ttypes.ErrorCode;
    public latency_in_us: Int64;
    public data?: common_ttypes.DataSet;
    public space_name?: string;
    public error_msg?: string;
    public plan_desc?: PlanDescription;
    public comment?: string;

      constructor(args?: { error_code: common_ttypes.ErrorCode; latency_in_us: Int64; data?: common_ttypes.DataSet; space_name?: string; error_msg?: string; plan_desc?: PlanDescription; comment?: string; });
  }

declare class AuthResponse {
    public error_code: common_ttypes.ErrorCode;
    public error_msg?: string;
    public session_id?: Int64;
    public time_zone_offset_seconds?: number;
    public time_zone_name?: string;

      constructor(args?: { error_code: common_ttypes.ErrorCode; error_msg?: string; session_id?: Int64; time_zone_offset_seconds?: number; time_zone_name?: string; });
  }

declare class VerifyClientVersionResp {
    public error_code: common_ttypes.ErrorCode;
    public error_msg?: string;

      constructor(args?: { error_code: common_ttypes.ErrorCode; error_msg?: string; });
  }

declare class VerifyClientVersionReq {
    public version?: string;

      constructor(args?: { version?: string; });
  }
